version: '3'

services:
  web1:
    build: ./web
    volumes:
      - ./web/server.js:/usr/app/server.js
  web2:
    build: ./web
    volumes:
      - ./web/server.js:/usr/app/server.js
  web3:
    build: ./web
    volumes:
      - ./web/server.js:/usr/app/server.js
  proxy:
    build: ./proxy
    environment:
      - SERVICES=web1 web2 web3
      - PORT=9000
    ports:
      - 9000:9000
    volumes:
      - ./proxy/server.js:/usr/app/server.js
