version: '3'

services:
  web1:
    build: ./web
    volumes:
      - ./web/server.js:/usr/app/server.js
    environment:
      - LOAD_BALANCER=proxy
  web2:
    build: ./web
    volumes:
      - ./web/server.js:/usr/app/server.js
    environment:
      - LOAD_BALANCER=proxy
  web3:
    build: ./web
    volumes:
      - ./web/server.js:/usr/app/server.js
    environment:
      - LOAD_BALANCER=proxy
  proxy:
    build: ./proxy
    environment:
      - PORT=9000
    ports:
      - 9000:9000
    volumes:
      - ./proxy/server.js:/usr/app/server.js

